---
- yum: name={{item}} state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  with_items:
    - firewalld
    - vim-enhanced
    - elinks
    - ntp
    - git
    - wget
    - unzip 
    - psmisc
    - libsemanage-python
    - ntp
- service: name={{item}} state=started enabled=yes
  with_items: 
    - ntpd

- name: Update the /etc/ssh/sshd_config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: EOF
    state: present
  register: ssh_config

- name: Restart ssh
  service:
    name: sshd
    state: restarted
  when: ssh_config.changed
